### ISSUE TITLE
Help with OpenHEVC Backport to FFMPEG Master

### ISSUE THREAD

**Issue by jlsantiago0** [OpenHEVC/openHEVC#1]
I have created a patch to backport OpenHEVC Decoder to the recent FFMPEG Master. The patch is located https://github.com/OpenHEVC/openHEVC/wiki/OpenHEVC-Decoder-Backport-to-FFMPEG-Master . I have an issue that hopefully someone familiar with the HEVC decoder internals can help with. The decoder seems to get stuck in an infinite loop. I am planning on debugging it. But I assume someone with direct experience with the decoder could fix it pretty easily. If ffplay could be encouraged to decode an .h265 file containing raw HEVC elementary stream, perhaps I could get FFMPEG to accept the patch.

**Comment by smarter** [comment]
> If ffplay could be encouraged to decode an .h265 file containing raw HEVC elementary stream, perhaps I could get FFMPEG to accept the patch.

Please don't do that. The HEVC decoder is not ready yet.  It will be eventually merged into libav and ffmpeg and you can already use the libav version at https://github.com/OpenHEVC/libav (some OpenHEVC changes have not been merged there yet). You're welcome to help with cleaning up the decoder and merging the OpenHEVC changes into OpenHEVC/libav .

**Comment by mraulet** [comment]
Agree with Guillaume.

Mickael

Sent by my iPhone
