### ISSUE TITLE
Performance in dequant.

### ISSUE THREAD

**Issue by pieter3d** [OpenHEVC/openHEVC#10]
Would it be faster to perform the dequant as each coefficient is decoded? Right now the whole TU is dequantized afterwards, and for typical video that means lots of operations on 0 coefficients. 

Doing dequant on the fly would result in way less operations, although it means no opportunity to use SSE2 routines....

**Comment by mraulet** [comment]
There is a rounding that you have to apply even on zero coefficients.

Mickael

Sent by my iPhone

**Comment by pieter3d** [comment]
Are you sure? I'm pretty sure that if a decoded coefficient is 0, then the dequant coefficient is always 0 too. This is how we have implemented a HW decoder and it does not have issues with that.

**Comment by mraulet** [comment]
pretty sure if x == 0 then you have to add "add" in the following code.

#define SCALE(dst, x) (dst) = av_clip_int16(((x) + add) >> shift)

__
Mickaël

**Comment by pieter3d** [comment]
Yes, but in that case the downshift will always obliterate whatever add was. "add" does not have any bit position set higher than shift

**Comment by mraulet** [comment]
you are right.
__
Mickaël
