### ISSUE TITLE
Mutithread decoding support

### ISSUE THREAD

**Issue by vkravets** [OpenHEVC/openHEVC#14]
Another H.265/HEVC (http://xhevc.com/en/hevc/decoder/keyFeatures.jsp) codes support Mutithread decoding and ffmpeg on my Phenom X3 (3.2GHz) load only one core and video playing icriediable slow.

**Comment by mraulet** [comment]
ffmpeg does not contain all optimzation part of openhevc, which version of ffmpeg are you using? from which branch?
__
Mickaël

**Comment by smarter** [comment]
Use ffmpeg with "-threads 2" if you want to use 2 threads for example. And note that the decoder is far from fully optimized yet, but progress is being made.
