### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [OpenHEVC/openHEVC#15]
Some parameters (like "[${CMAKE_CURRENT_SOURCE_DIR}](https://github.com/OpenHEVC/openHEVC/blob/bc6844ff24695a1f716bae131e783faf4e37cfb0/CMakeLists.txt#L20)" and "[${SDL_INCLUDE_DIR}](https://github.com/OpenHEVC/openHEVC/blob/991dce8fadd586a99c3a89f27f841fcda12faaa7/wrapper_hm/CMakeLists.txt#L19)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like spaces.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by mraulet** [comment]
The plan is to refactor the cmake_list we were just discussing it just before receiving your email.
__
Mickaël
