### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by hfzp** [OpenHEVC/openHEVC#18]
Hi,

I am interested for support for ARM architecture. Will there be a support for it? at least on the near future on the roadmap?. I saw that there is a notable amount of x86-specific code. So, do you have a rough estimates of the time/effort required to port it to ARM?, or is it even feasible at this time with the currently available hardware and api/library support ?.

BTW, have asked this on libav-devel and there is no reply so far, so I though I try asking here. I hope it's alright. 

Thanks

**Comment by mraulet** [comment]
The decoder has already been ported to ARM platforms and we already have optimizations running for some functions see https://github.com/OpenHEVC/openHEVC/tree/hevc_arm.

**Comment by hfzp** [comment]
Cool!. I didn't notice the branch before. Thank you very much for pointing it out.
