### ISSUE TITLE
OpenHEVC Decoder Outputs Frames in Wrong Order from DPB

### ISSUE THREAD

**Issue by jlsantiago0** [OpenHEVC/openHEVC#2]
This was tested with OpenHEVC hevc Decoder application HEAD of hm10.0 branch. Bitstreams demonstrating this issue can be downloaded from:

wget http://208.51.85.91/hevc-openhevc-decoder-wrong-output-order.tar.bz2

This archive is 3MB containing three H.265 elementary stream files. The files contain 3 b-frames per p-frame which differ from the reference bitstreams which seem to contain at most 2 b-frames per p-frame.

Elecard is able to determine the correct frame order.

**Comment by mraulet** [comment]
I have merged the current work into hm10.0. I tried and it seems to decode exactly the same than the HM. We might correct the bug in the other branch :-). Could you have a look?

Thanks
__
Mickaël

**Comment by jlsantiago0** [comment]
Issue is resolved after your recent changes. Thank You!
