### ISSUE TITLE
Issue when compiling arm

### ISSUE THREAD

**Issue by romdhann** [OpenHEVC/openHEVC#20]
I'm trying to compile HEVC in with armv7 machine and i have the following error would you please help me to resolve it:
/home/linaro/HEVC/openHEVC/libavutil/random_seed.c: In function ‘av_get_random_seed’:
/home/linaro/HEVC/openHEVC/./libavutil/x86/timer.h:33:5: error: impossible constraint in ‘asm’
/home/linaro/HEVC/openHEVC/./libavutil/x86/timer.h:33:5: error: impossible constraint in ‘asm’
make[2]: **\* [CMakeFiles/LibOpenHevcWrapper.dir/libavutil/random_seed.c.o] Error 1
make[1]: **\* [CMakeFiles/LibOpenHevcWrapper.dir/all] Error 2
make: **\* [all] Error 2

The strange things that I sse in my code that this build is compiling x86 files which is not logical,normally  we compile only arm files,thanks to help me :(

**Comment by mraulet** [comment]
could you report the message within cmake?
__
Mickaël

**Comment by mraulet** [comment]
can you try this branch for the moment hevc_arm? I will ask to try here. This branch is not far from mainstream. 
__
Mickaël

**Comment by romdhann** [comment]
Hi Mickaël,
I've tried the arm branch and the compilation is still running for x86 and not for arm.
For the  cmake this is the coammnde that i have used:  cmake -DCMAKE_TOOLCHAIN_FILE=../arm-gnueabi.toolchain.cmake ../../..

**Comment by mraulet** [comment]
We haven't try cross compilation, but direct compilation on the board. I hope this help. 
__
Mickaël

**Comment by michalliu** [comment]
same issue, has anyone resolved the problem?
