### ISSUE TITLE
Fail to configure OpenHEVC under Ubuntu 14.04 on my desktop.

### ISSUE THREAD

**Issue by jiapei100** [OpenHEVC/openHEVC#21]
Hi, 

I'm getting the following error messages:

 CMake Warning at MyCMakeScripts/OptimizeForArchitecture.cmake:114 (message):
   Your CPU (family 6, model 60) is not known.  Auto-detection of optimization
   flags failed and will use the 65nm Core 2 CPU settings.
 Call Stack (most recent call first):
   MyCMakeScripts/OptimizeForArchitecture.cmake:163 (AutodetectHostArchitecture)
   CMakeLists.txt:26 (OptimizeForArchitecture)

It looks OpenHEVC has something to do with the CPU ? Does that mean my CPU is too strong to configure OpenHEVC?

Cheers
Pei

**Comment by alorence** [comment]
Can you provide information on your CPU (Model, Family, etc.) ?

**Comment by jiapei100** [comment]
Hi:

Thank you so much for your prompt reply.
my cpuinfo is:

➜  ~  cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 1
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 2
cpu cores       : 4
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 1
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 6
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 2
cpu cores       : 4
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
stepping        : 3
microcode       : 0x7
cpu MHz         : 800.000
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl
xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb
xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase
tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 7000.66
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

On Mon, Jun 23, 2014 at 3:07 PM, Antoine Lorence notifications@github.com
wrote:

> Can you provide information on your CPU (Model, Family, etc.) ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenHEVC/openHEVC/issues/21#issuecomment-46812090.

## 

Pei JIA

Email: jp4work@gmail.com
cell:    +1 604-362-5816

Welcome to Vision Open
http://www.visionopen.com

**Comment by alorence** [comment]
Can you test the patch from commit 712933950c9 ? It was pushed on hevc_rext branch. You can also cherry-pick if you are working on another branch

**Comment by jiapei100** [comment]
Wow... such a prompt reply... Thank you !!

1)
When cmake, I got
 DEBUG: CMAKE_SYSTEM_PROCESSOR = x86_64

 DEBUG: CMAKE_SYSTEM_NAME      = Linux

2)
while make, I got

[ 92%] Building C object
CMakeFiles/LibOpenHevcWrapper.dir/libavcodec/x86/hevc_sao_sse.c.o
...../OpenHEVC/openHEVC/libavcodec/x86/hevc_sao_sse.c: In function
‘ff_hevc_sao_edge_filter_8_sse’:
...../OpenHEVC/openHEVC/libavcodec/x86/hevc_sao_sse.c:369:20: error:
incompatible types when assigning to type ‘__m128i’ from type ‘int’
                 r0 = _mm_cvtepi8_epi16(r0);
                    ^
make[2]: ***
[CMakeFiles/LibOpenHevcWrapper.dir/libavcodec/x86/hevc_sao_sse.c.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [CMakeFiles/LibOpenHevcWrapper.dir/all] Error 2
make: **\* [all] Error 2

cheers
Pei

On Mon, Jun 23, 2014 at 4:45 PM, Antoine Lorence notifications@github.com
wrote:

> Can you test the patch from commit 7129339
> https://github.com/OpenHEVC/openHEVC/commit/712933950c9 ? It was pushed
> on hevc_rext branch. You can also cherry-pick if you are working on another
> branch
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenHEVC/openHEVC/issues/21#issuecomment-46819157.

## 

Pei JIA

Email: jp4work@gmail.com
cell:    +1 604-362-5816

Welcome to Vision Open
http://www.visionopen.com

**Comment by mraulet** [comment]
did you clean up with cmake? According to me you are still falling in core2 duo CPU. I have to fix SAO any way in order to make it core 2 duo compliant.
__
Mickaël

**Comment by mraulet** [comment]
it is now updated on the main branch (hevc_rext). Could you report if it detects well an haswell processor in your case?
__
Mickaël

**Comment by jiapei100** [comment]
Yup. You are right.
I now have OpenHEVC successfully built...
Thank you so much...

Cheers
Pei

On Mon, Jun 23, 2014 at 5:22 PM, Mickaël Raulet notifications@github.com
wrote:

> it is now updated on the main branch (hevc_rext). Could you report if it
> detects well an haswell processor in your case?
> __
> Mickaël
> 
> Le 23 juin 2014 à 10:59, Mickaël Raulet Mickael.Raulet@insa-rennes.fr a
> écrit :
> 
> > did you clean up with cmake? According to me you are still falling in
> > core2 duo CPU. I have to fix SAO any way in order to make it core 2 duo
> > compliant.
> > __
> > Mickaël
> > 
> > Le 23 juin 2014 à 10:52, JIA Pei notifications@github.com a écrit :
> > 
> > > Wow... such a prompt reply... Thank you !!
> > > 
> > > 1)
> > > When cmake, I got
> > > DEBUG: CMAKE_SYSTEM_PROCESSOR = x86_64
> > > 
> > > DEBUG: CMAKE_SYSTEM_NAME = Linux
> > > 
> > > 2)
> > > while make, I got
> > > 
> > > [ 92%] Building C object
> > > CMakeFiles/LibOpenHevcWrapper.dir/libavcodec/x86/hevc_sao_sse.c.o
> > > ...../OpenHEVC/openHEVC/libavcodec/x86/hevc_sao_sse.c: In function
> > > ‘ff_hevc_sao_edge_filter_8_sse’:
> > > ...../OpenHEVC/openHEVC/libavcodec/x86/hevc_sao_sse.c:369:20: error:
> > > incompatible types when assigning to type ‘__m128i’ from type ‘int’
> > > r0 = _mm_cvtepi8_epi16(r0);
> > > ^
> > > make[2]: ***
> > > [CMakeFiles/LibOpenHevcWrapper.dir/libavcodec/x86/hevc_sao_sse.c.o]
> > > Error 1
> > > make[2]: **\* Waiting for unfinished jobs....
> > > make[1]: **\* [CMakeFiles/LibOpenHevcWrapper.dir/all] Error 2
> > > make: **\* [all] Error 2
> > > 
> > > cheers
> > > Pei
> > > 
> > > On Mon, Jun 23, 2014 at 4:45 PM, Antoine Lorence <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Can you test the patch from commit 7129339
> > > > https://github.com/OpenHEVC/openHEVC/commit/712933950c9 ? It was
> > > > pushed
> > > > on hevc_rext branch. You can also cherry-pick if you are working on
> > > > another
> > > > branch
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/OpenHEVC/openHEVC/issues/21#issuecomment-46819157.
> > > 
> > > ## 
> > > 
> > > Pei JIA
> > > 
> > > Email: jp4work@gmail.com
> > > cell: +1 604-362-5816
> > > 
> > > Welcome to Vision Open
> > > http://www.visionopen.com
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenHEVC/openHEVC/issues/21#issuecomment-46822466.

## 

Pei JIA

Email: jp4work@gmail.com
cell:    +1 604-362-5816

Welcome to Vision Open
http://www.visionopen.com
