### ISSUE TITLE
complie HEVC on ARM

### ISSUE THREAD

**Issue by darkmiss** [OpenHEVC/openHEVC#24]
Hi,
l download the ZIP file on 
I was trying to build HEVC on ARM,
I tried the following
1. mkdir build
2. cd build
3. cmake -DCMAKE_BUILD_TYPE=RELEASE ..
4. make verbose=1

AND I GOT the following message

...
...
...
...
/usr/bin/cc   -DUSE_SDL -O3 -DNDEBUG    CMakeFiles/hevc.dir/main_hm/getopt.c.o Cl,-Bstatic -lSDLmain -Wl,-Bdynamic -lSDL -lpthread

/usr/bin/ld.bfd.real: libLibOpenHevcWrapper.a(utils.c.o): undefined reference to
//lib/arm-linux-gnueabihf/libm.so.6: error adding symbols: DSO missing from comm
collect2: error: ld returned 1 exit status

**Comment by mraulet** [comment]
do you have more verbose message? Can you let us know what cmake is outputting? which platform you are running on? Do you use cross compilation?
__
Mickaël

**Comment by darkmiss** [comment]
I  compile HEVC_arm on ODROID. 

I use "lsb_release -a"
GOT the following message
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

The verbose message is in the website as following 
http://www.cs.ccu.edu.tw/~wcw99u/DEBUG_imformation.txt

DEBUG: CMAKE_SYSTEM_PROCESSOR = armv7l
DEBUG: CMAKE_SYSTEM_NAME = Linux

I try to google the error, lots of answer is "the file can't link"
and the sulotion is to add -ldl in the makefile or in the CMakeList.txt,
but I can't find the correct place to add.

 _
                                              Louis

**Comment by alorence** [comment]
Can you try to add the following line in your CMakeLists.txt (line 306, just after the bloc defining LibOpenHevcWrapper target):

```
target_link_libraries(LibOpenHevcWrapper m)
```

and post here your feedback? If it fixes your issue, we will push this fix

**Comment by darkmiss** [comment]
It works!!!!!!
I now have OpenHEVC successfully built...
Thank you so much...

Cheers
Louis
