### ISSUE TITLE
Missing references trying to compile shm-dev branch

### ISSUE THREAD

**Issue by hrhelena** [OpenHEVC/openHEVC#36]
Hi, I'm trying to compile shm-dev branch and I'm getting some undefined references.
Do you know what I'm i missing?

This is the cmake output: 
cmake -DCMAKE_BUILD_TYPE=RELEASE -DENABLE_STATIC=OFF  ..

DEBUG: CMAKE_SYSTEM_PROCESSOR = armv7l
DEBUG: CMAKE_SYSTEM_NAME      = Linux
-- Detected CPU: generic
-- Found components for YASM
-- YASM_ROOT_DIR  = /usr/local
-- YASM_INCLUDES  = /usr/include
-- YASM_LIBRARIES = YASM_LIBRARIES-NOTFOUND
-- Performing Test check_c_compiler_flag__fpic
-- Performing Test check_c_compiler_flag__fpic - Success
-- Performing Test check_c_compiler_flag__fno_tree_vectorize
-- Performing Test check_c_compiler_flag__fno_tree_vectorize - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/shm-dev/build

And here is the make output:

...........
Linking C shared library libLibOpenHevcWrapper.so
[ 95%] Built target LibOpenHevcWrapper
Scanning dependencies of target hevc
[ 96%] Building C object CMakeFiles/hevc.dir/main_hm/getopt.c.o
[ 96%] Building C object CMakeFiles/hevc.dir/main_hm/main.c.o
[ 97%] Building C object CMakeFiles/hevc.dir/main_hm/sdl.c.o
[ 97%] Building C object CMakeFiles/hevc.dir/main_hm/SDL_framerate.c.o
Linking C executable hevc
libLibOpenHevcWrapper.so: undefined reference to `ff_svq3_add_idct_c'
libLibOpenHevcWrapper.so: undefined reference to`ff_hpeldsp_init_armv6'
libLibOpenHevcWrapper.so: undefined reference to `ff_svq3_luma_dc_dequant_idct_c'
libLibOpenHevcWrapper.so: undefined reference to`ff_er_add_slice'
libLibOpenHevcWrapper.so: undefined reference to `ff_me_cmp_init'
libLibOpenHevcWrapper.so: undefined reference to`ff_er_frame_end'
libLibOpenHevcWrapper.so: undefined reference to `ff_print_debug_info2'
libLibOpenHevcWrapper.so: undefined reference to`ff_er_frame_start'
libLibOpenHevcWrapper.so: undefined reference to `ff_imdct_half_vfp'
collect2: error: ld returned 1 exit status
make[2]: **\* [hevc] Error 1
make[1]: **\* [CMakeFiles/hevc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by eraffin** [comment]
Hi, it should be fixed. Could you check on your side?

**Comment by hrhelena** [comment]
Yes , thanks. Now it works.

**Comment by NitinChaudharyUSC** [comment]
Hi, I am also facing similar issue, Could you please confirm the fix for this issue on hevc_rext while doing cross-compilation on Ubuntu x86 for ARM Cortex A9 using arm-linux-gnueabihf-\* toolchain?
