### ISSUE TITLE
Can not compile the newest code!

### ISSUE THREAD

**Issue by alaiyeshi** [OpenHEVC/openHEVC#4]
error content :

Linking C executable hevc
libLibOpenHevcWrapper.so: undefined reference to `ff_cpu_xgetbv'
libLibOpenHevcWrapper.so: undefined reference to`ff_cpu_cpuid'

**Comment by mraulet** [comment]
fixed in the latest commit

**Comment by PandaWood** [comment]
I had to go looking for this commit (to learn something) so thought I'd post it here for anyone else... I believe this is the commit referred to:
https://github.com/OpenHEVC/openHEVC/commit/5a7d0e750c17f3abe438379f2bf9b70b4c557331
