### ISSUE TITLE
openHEVC compile error

### ISSUE THREAD

**Issue by JWSon** [OpenHEVC/openHEVC#47]
Hi :)
I got the fllowing error when trying to compile the makefile on Ubuntu.

sudo make install
[ 96%] Built target LibOpenHevcWrapper
[ 97%] Linking C executable hevc
/usr/bin/ld: libLibOpenHevcWrapper.a(eval.c.o): undefined reference to symbol 'fabs@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/hevc.dir/build.make:175: recipe for target 'hevc' failed
make[2]: **\* [hevc] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/hevc.dir/all' failed
make[1]: **\* [CMakeFiles/hevc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

I look forward to your responses.
Thanks!
Regard,
Son

**Comment by pcabarat** [comment]
Hi!
You should have a look at this pull request: 
https://github.com/OpenHEVC/openHEVC/pull/43/commits/8c959b24c827eb8ed0d68034fc0e89fa851a3ce8
It should fix your issue.

Regards,
Pierre-Loup
