### ISSUE TITLE
Using cpu_set_t  in Android branch

### ISSUE THREAD

**Issue by yeongil** [OpenHEVC/openHEVC#52]
Hello.

I am trying to use cpu_set_t struct and CPU_ZERO macro in OpenHEVC android branch.
cpu_set_t struct and CPU_ZERO macro is used in libavutil/cpu.c already.
but, I can not use them in main_hm/main.c file.
There is undeclared identifier error at 'cpu_set_t'.

How can I solve this problem.
I need your help absolutely.
Please help me.

Thank you.

**Comment by pcabarat** [comment]
Hello.
The android branch is rather old. 
I don't really understand why you'd want to use those into the main_hm/main.c 
Considering your problem:
    -cpu_set_t is neither declared nor defined by openHEVC or FFmpeg. Try to have a look on how it is included into libavutil/cpu.c. On my configuration it is located into sched.h. Depending on your configuration it might be located elsewhere on your computer. If not already done you can try to include it from the main.h.
You might also want to include config.h into our main if not already done. 
Then there might also be something wrong with the cmake generated config.h.

Pierre-Loup

**Comment by yeongil** [comment]
Hello.

Additionally, I confirmed that 'cpu_set_t' and 'sched_setaffinity()' are included in libc of bionic.
They are basically provided by libc library.
Why I Can not use the 'cpu_set_t' and 'sched_setaffinity()'?
How can I link and use the libc in OpenHEVC android branch?
Please help me...

Thank you.

**Comment by pcabarat** [comment]
I don't really know about the build infrastructure we use for arm, especially on this branch. It is an old version of openHEVC. You can have a look to how things are done on the green branch maybe.
However I still don't understand why you'd want to use scheduling related function in the main.c.
The main.c  only consists of a demo on how to use the lib.

**Comment by yeongil** [comment]
Hello.

I resolve the problem to try several way.

"#define _gnu_source" and "#include <sched.h>" work correctly to replace "APP_ABI:=armeabi"  to "APP_ABI:=arm64-v8a" and "LOCAL_SDK_VERSION:=23" at "Android.mk" in my case.

Thank you for your responses.

Good luck.
