### ISSUE TITLE
HEVC decoder crashes on dual core machine...

### ISSUE THREAD

**Issue by ssmedia** [OpenHEVC/openHEVC#7]
When we run hevc decoder on a Dual Core machine (without SSE4 extension), it crashes saying "Illegal instruction". Using gdb we found that it crashes in "ff_hevc_transform_8x8_add_8_sse4 ()" found in "libavcodec/x86/hevc_idct_sse4.c". Is it possible that it can detect the CPU extensions available at runtime and accordingly fallback to less power full extension. Pls find the details below:
OS: FC18 64-bit
CPU details: model name : Intel(R) Pentium(R) Dual  CPU  E2180  @ 2.00GHz
CPU flags: fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm lahf_lm

**Comment by mraulet** [comment]
Could you try our fork of libav? And let me know if it works. In terms of functionality it is aligned with openhevc.

Mickael

Sent by my iPhone

**Comment by ssmedia** [comment]
We tried the libav fork as well, but the results are same. It crashes with "SIGILL". The log is as follow:

GNU gdb (GDB) Fedora (7.5.1-32.fc18)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /root/libav_git/avplay...done.
(gdb) run test.hevc
Starting program: /root/libav_git/avplay test.hevc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff7fe1700 (LWP 13615)]
[New Thread 0x7ffff760b700 (LWP 13616)]
[New Thread 0x7ffff2c02700 (LWP 13617)]
[Thread 0x7ffff2c02700 (LWP 13617) exited]
[New Thread 0x7ffff2c02700 (LWP 13618)]

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff2c02700 (LWP 13618)]
ff_hevc_transform_8x8_add_8_sse4 (_dst=0x7ffff6755af0 "34543/*#", coeffs=0x7ffff2c00ad0, 
    _stride=480) at libavcodec/x86/hevc_idct_sse4.c:543
543     E0l = _mm_unpacklo_epi8(E0l, _mm_setzero_si128());
Missing separate debuginfos, use: debuginfo-install SDL-1.2.15-3.fc18.x86_64 alsa-lib-1.0.26-2.fc18.x86_64 alsa-plugins-pulseaudio-1.0.26-2.fc18.x86_64 dbus-libs-1.6.8-2.fc18.x86_64 flac-1.2.1-10.fc18.x86_64 glibc-2.16-28.fc18.x86_64 gsm-1.0.13-7.fc18.x86_64 json-c-0.10-2.fc18.x86_64 libICE-1.0.8-2.fc18.x86_64 libSM-1.2.1-2.fc18.x86_64 libX11-1.5.99.901-3.20130524gita3bdd2b09.fc18.x86_64 libXau-1.0.6-4.fc18.x86_64 libXext-1.3.1-3.20130524gitdfe6e1f3b.fc18.x86_64 libXi-1.6.1-2.fc18.x86_64 libXrandr-1.4.0-4.20130524gitc90f74497.fc18.x86_64 libXrender-0.9.7-5.20130524git786f78fd8.fc18.x86_64 libXtst-1.2.1-3.fc18.x86_64 libasyncns-0.8-4.fc18.x86_64 libogg-1.3.0-2.fc18.x86_64 libsndfile-1.0.25-4.fc18.x86_64 libuuid-2.22.1-2.4.fc18.x86_64 libvorbis-1.3.3-3.fc18.x86_64 libxcb-1.9-3.fc18.x86_64 pulseaudio-libs-2.1-5.fc18.x86_64 tcp_wrappers-libs-7.6-70.fc18.x86_64 zlib-1.2.7-9.fc18.x86_64

**Comment by mraulet** [comment]
in hevcdsp_init.c

if you comment those lines does it work?

```
                        c->transform_4x4_luma_add = ff_hevc_transform_4x4_luma_add_8_sse4;

                c->transform_add[0] = ff_hevc_transform_4x4_add_8_sse4;
                c->transform_add[1] = ff_hevc_transform_8x8_add_8_sse4;
                c->transform_add[2] = ff_hevc_transform_16x16_add_8_sse4;
                c->transform_add[3] = ff_hevc_transform_32x32_add_8_sse4;
```

__
Mickaël

**Comment by ssmedia** [comment]
When we comment the 5 lines mentioned above, it decodes around 10 frames and crashes with "SIGILL" again. The short log is as follows:

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff57dd700 (LWP 1953)]
ff_hevc_put_hevc_qpel_v_1_8_sse (dst=0x7ffff57d8980, dststride=<optimized out>, 
    _src=<optimized out>, _srcstride=480, width=8, height=16, mcbuffer=0x19bd0a0)
    at libavcodec/x86/hevc_mc_sse.c:2384
2384                    x1 = _mm_unpacklo_epi8(x1, t8);
Missing separate debuginfos, use: debuginfo-install alsa-lib-1.0.26-2.fc18.x86_64 glibc-2.16-28.fc18.x86_64 zlib-1.2.7-9.fc18.x86_64

---

Now if we comment "c->put_hevc_qpel[1][0] = ff_hevc_put_hevc_qpel_v_1_8_sse;" in "libavcodec/x86/hevcdsp_init.c", it crashes with "SIGILL" at some different location. The short log is as follows:

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff57dd700 (LWP 2107)]
ff_hevc_put_unweighted_pred_8_sse (_dst=<optimized out>, dststride=240, src=0x7ffff57d8980, 
    srcstride=<optimized out>, width=4, height=8) at libavcodec/x86/hevc_mc_sse.c:63
63                      r0 = _mm_adds_epi16(r0, f0);
Missing separate debuginfos, use: debuginfo-install alsa-lib-1.0.26-2.fc18.x86_64 glibc-2.16-28.fc18.x86_64 zlib-1.2.7-9.fc18.x86_64

---

**Comment by ssmedia** [comment]
We compiled latest openHEVC on FC18 32-it machine. In this case, the hevc binary doesn't crashes on my dual core machine.

**Comment by mraulet** [comment]
so we can close the ticket?
__
Mickaël

**Comment by ssmedia** [comment]
Yes, you can. Thnx for your support...
